### ISSUE TITLE
Checkpoints link

### ISSUE THREAD

**Issue by MohannadEhabBarakat** [sanviiz/hairstyle-try-on#2]
Hi, Nice work. I was trying to run the colab test and found out that the checkpoints link is not working (https://image-editing-test-12345.s3-us-west-2.amazonaws.com/checkpoints/celeba_hq.ckpt). Is there any other link I can use?

**Comment by sorayutmild** [comment]
The checkpoint for the model was taken from SDEdit at https://github.com/ermongroup/SDEdit. From there, you could find the updated link.

**Comment by MohannadEhabBarakat** [comment]
Thanks
