### ISSUE TITLE
Checkpoints  checkpoints/celeba_hq.ckpt  are not accessible.

### ISSUE THREAD

**Issue by faisalimran2018** [sanviiz/hairstyle-try-on#3]
I am trying to download the  "checkpoints/celeba_hq.ckpt this link (https://image-editing-test-12345.s3-us-west-2.amazonaws.com/checkpoints/celeba_hq.ckpt)  but this link says "access denied", could you please update the link to a google drive one or provide access to these weights.

**Comment by phalapat** [comment]
The checkpoint for the model was taken from SDEdit at https://github.com/ermongroup/SDEdit. From there, you could find the updated link.
[or this link](https://github.com/wyhuai/DDNM/issues/34#issuecomment-1501742924)

**Comment by faisalimran2018** [comment]
https://drive.google.com/file/d/1wSoA5fm_d6JBZk4RZ1SzWLMgev4WqH21/view?usp=share_link


this is the link just copying here so that it can be used in the future.
