### ISSUE TITLE
import the code 

### ISSUE THREAD

**Issue by pathak7874** [sanviiz/hairstyle-try-on#7]
please help in i am waiting Create checkpoints folder and Download checkpoints/celeba_hq.ckpt  from [this link](https://image-editing-test-12345.s3-us-west-2.amazonaws.com/checkpoints/celeba_hq.ckpt) than put it in checkpoints this code not download please help urgent help me

**Comment by sorayutmild** [comment]
The checkpoint for the model was taken from SDEdit. You may read this issues https://github.com/sanviiz/hairstyle-try-on/issues/3
